name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install automake
      if: ${{ matrix.os == 'macos-latest' }}
      run: |
        brew update
        brew install automake

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.x # Version range or exact version of a Python version to use, using SemVer's version range syntax

    - name: Install meson
      run: |
        python -m pip install --upgrade pip
        pip install meson ninja

    - name: Install FFmpeg
      run: |
        git clone https://github.com/AkarinVS/FFmpeg --branch lsmas-4.5 --depth 1
        pushd FFmpeg
        # If you want to build lsmas for encoding, the recommended configure
        # arguments are as follows:
        # --enable-gpl --enable-version3 --enable-static --disable-shared \
        # --enable-avcodec --enable-avformat --enable-swresample --enable-swscale \
        # --disable-programs --disable-avdevice --disable-postproc --disable-avfilter \
        # --disable-encoders --disable-muxers --disable-doc --disable-debug \
        # --enable-libdav1d --enable-zlib \
        # --enable-cuvid --enable-ffnvcodec --enable-libmfx
        # Remove the last line if you don't need hardware accelerated decoding.
        ./configure --enable-gpl --enable-version3 --disable-static --enable-shared --disable-all --disable-autodetect --enable-avcodec --enable-avformat --enable-swresample --enable-swscale --disable-asm --disable-debug
        make -j2
        sudo make install -j2
        popd
        rm -rf FFmpeg

    - name: Install l-smash
      run: |
        git clone https://github.com/l-smash/l-smash --depth 1
        pushd l-smash
        mv configure configure.old
        sed 's/-Wl,--version-script,liblsmash.ver//g' configure.old >configure
        chmod +x configure
        ./configure --disable-static
        make lib -j2
        sudo make install-lib -j2
        popd
        rm -rf l-smash

    - name: Install AviSynth
      run: |
        git clone https://github.com/AviSynth/AviSynthPlus --branch 3.7 --depth 1 avisynth-build
        pushd avisynth-build
        cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DENABLE_PLUGINS=OFF -DENABLE_INTEL_SIMD=OFF
        cmake --build build -j 2
        sudo cmake --install build
        popd
        rm -rf avisynth-build

    - name: Build AviSynth plugin
      run: |
        pushd AviSynth
        meson build
        ninja -C build
        popd

    - name: Install zimg
      run: |
        git clone https://github.com/sekrit-twc/zimg --branch v3.0 --depth 1
        pushd zimg
        ./autogen.sh
        ./configure --disable-static --disable-simd
        make -j2
        sudo make install -j2
        popd
        rm -rf zimg

    - name: Install VapourSynth
      run: |
        git clone https://github.com/vapoursynth/vapoursynth --branch api3 --depth 1 vapoursynth-build
        pushd vapoursynth-build
        ./autogen.sh
        ./configure --disable-static --disable-x86-asm --disable-vsscript --disable-vspipe --disable-python-module --disable-plugins
        make -j2
        sudo make install -j2
        popd
        rm -rf vapoursynth-build

    - name: Build VapourSynth plugin
      run: |
        pushd VapourSynth
        meson build
        ninja -C build
        popd
